services:
  api-tests:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    image: docker-api-tests
    container_name: docker-api-tests-instance
    command: python3 run.py
    ports:
      - "8089:8089"
    volumes:
      - docker-api-data:/app/data
      - ./logs:/var/log
    stdin_open: true
    tty: true
    restart: "no"

volumes:
  docker-api-data:
    name: docker-api-data